In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [5]:
df.groupby('Company')

In [26]:
grp = df.groupby("Company")

Using Above code this will return the memory address where the data is grouped

In [24]:
df.groupby('Company').sum()

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [8]:
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [28]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0